### ISSUE TITLE
Inconsistant name for the "detection" task

### ISSUE THREAD

**Issue by APoinas** [jmiramont/benchmarks-detection-denoising#7]
There is a minor issue at line 135 in Benchmark.py. The instructions on the demo_benchmark notebook says to use the parameter task="detecting" when using the benchmark but when you do it you get an error also telling you to use the parameter task="detecting". It turns out that the name expected in the code is "detection" and not "detecting".

```
if (task != 'denoising' and task != 'detection'):
     raise ValueError("The tasks should be either 'denoising' or 'detecting'.\n")
```

**Comment by jmiramont** [comment]
Thanks! The task will be identified by the string 'detection'.
